.PHONY: external

SHELL=bash -e
STATIC_DIR=showdocs/static

tests:
	nosetests tests/
	cram tests/

externalcss:
	[ -d $(STATIC_DIR) ]
	wrap () { \
		echo "/* DO NOT EDIT auto-generated by 'make external' */"; \
		echo; \
		echo "#docs {"; \
		cat "$$1"; \
		echo "}"; \
	}; \
	for f in $$(find external -name '*.css'); do \
		frelative=$${f:9}; \
		mkdir -p $$(dirname $(STATIC_DIR)/external/$$frelative); \
		wrap $$f > /tmp/foo.scss; \
		scss --sourcemap=none <(wrap $$f) $(STATIC_DIR)/external/$$frelative; \
		[ -f $(STATIC_DIR)/external/$$frelative ]; \
	done

clean:
	rm -r externaltmp/ || true
	find showdocs tests external -name '*.py[cdo]' -exec rm -f '{}' ';'

.PHONY: clean externalcss tests
